service: redis
---
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/NETTY?characterEncoding=UTF-8
    username: root
    password: qkrghkfks
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
---
spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      host: 192.168.88.123
      port: 6379
      password: redis
      key: log_table_
---
logging.file.path: D:/logs