spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/NETTY?characterEncoding=UTF-8
    username: root
    password: qkrghkfks
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect

logging.file.path: D:/logs