service: redis
---
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/NETTY?characterEncoding=UTF-8
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
---
spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      host: 
      port: 
      password: 
      key: 
---
logging.file.path: D:/logs
